import express from 'express'
import cors from 'cors'
import helmet from 'helmet'
import rateLimit from 'express-rate-limit'
import dotenv from 'dotenv'
import nodemailer from 'nodemailer'
import { initSchema, hasDatabase, query } from './server/db.js'
import { authenticate, hashPassword } from './server/auth.js'
import { uid, generateToken } from './server/ids.js'
import authRoutes from './server/routes/auth.js'
import schoolRoutes from './server/routes/school.js'
import organizationRoutes from './server/routes/organization.js'
import logsRoutes from './server/routes/logs.js'
import parentRoutes from './server/routes/parent.js'
import contactRoutes, { handleInboundWebhook } from './server/routes/contact.js'
import reviewsRoutes from './server/routes/reviews.js'
import { escapeHtml } from './server/html.js'

dotenv.config()

const app = express()
const port = process.env.PORT || 10000



// General rate limiting for API endpoints
const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // 100 requests per windowMs
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many requests. Please try again later.' },
})

// Stricter rate limiting for email endpoints
const emailLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 hour
  max: 20, // 20 emails per hour
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many email requests. Please try again later.' },
})

app.set('trust proxy', 1)
app.use(helmet())
app.use(cors({
  origin: [
    ...(process.env.FRONTEND_URL ? [process.env.FRONTEND_URL] : []),
    'http://localhost:5173',
    'http://localhost:10000',
  ],
  credentials: true,
}))

// Registered ahead of express.json() — Resend webhook signature
// verification needs the raw request body, which express.json() would
// otherwise already have consumed by the time a router saw it.
app.post('/api/contact/inbound', express.raw({ type: 'application/json' }), handleInboundWebhook)

app.use(express.json({ limit: '1mb' }))
app.use(apiLimiter)
app.use(authenticate)

// Server-backed accounts & (later) school dashboards.
app.use('/api/auth', apiLimiter, authRoutes)
app.use('/api/school', apiLimiter, schoolRoutes)
app.use('/api/organization', apiLimiter, organizationRoutes)
app.use('/api/logs', apiLimiter, logsRoutes)
app.use('/api/parent', apiLimiter, parentRoutes)
app.use('/api/contact', apiLimiter, contactRoutes)
app.use('/api/reviews', apiLimiter, reviewsRoutes)

// In-memory ring buffer of the most recently generated recovery codes. In
// production these are also emailed to the user; the buffer allows the
// password-reset endpoint to verify the code when the user submits it from
// the same browser (where it was already stored in localStorage).
const isProd = process.env.NODE_ENV === 'production'
const devCodeLog = []
const DEV_LOG_LIMIT = 25

function logDevCode(entry) {
  devCodeLog.unshift(entry)
  if (devCodeLog.length > DEV_LOG_LIMIT) devCodeLog.length = DEV_LOG_LIMIT
}

function transporter() {
  const host = process.env.EMAIL_HOST
  const smtpPort = Number(process.env.EMAIL_PORT || 587)
  const user = process.env.EMAIL_USER
  const pass = process.env.EMAIL_PASSWORD

  if (!host || !user || !pass) {
    return { transport: null, missing: missingVars({ host, user, pass }) }
  }

  return {
    transport: nodemailer.createTransport({
      host,
      port: smtpPort,
      secure: process.env.EMAIL_SECURE === 'true',
      auth: { user, pass },
    }),
    missing: [],
  }
}


function missingVars({ host, user, pass }) {
  const missing = []
  if (!host) missing.push('EMAIL_HOST')
  if (!user) missing.push('EMAIL_USER')
  if (!pass) missing.push('EMAIL_PASSWORD')
  return missing
}

// Lightweight status endpoint so the UI can show real setup hints instead of
// a generic "not configured" message.
app.get('/api/recovery-status', (_req, res) => {
  const { transport, missing } = transporter()
  res.json({
    smtpConfigured: Boolean(transport),
    missingVars: missing,
    devMode: !isProd,
    devCodeCount: devCodeLog.length,
  })
})

// Verify a recovery code and update the password in the database. The code
// was previously generated by the frontend, stored in localStorage, and sent
// via email. This endpoint lets the same browser complete the reset without
// waiting for the email to arrive.
app.post('/api/auth/reset-password', emailLimiter, async (req, res) => {
  const { email, code, newPassword } = req.body

  if (!email || typeof email !== 'string' || !email.includes('@') || email.length > 254) {
    return res.status(400).json({ error: 'Invalid email.' })
  }
  if (!code || typeof code !== 'string' || code.length > 20) {
    return res.status(400).json({ error: 'Invalid code.' })
  }
  if (!newPassword || typeof newPassword !== 'string' || newPassword.length < 8 || newPassword.length > 128) {
    return res.status(400).json({ error: 'Password must be at least 8 characters.' })
  }

  if (!hasDatabase()) {
    return res.status(503).json({ error: 'Server database is not configured.' })
  }

  try {
    const { rows } = await query('SELECT * FROM users WHERE email = $1', [email.trim().toLowerCase()])
    if (rows.length === 0) {
      return res.status(404).json({ error: 'No account with that email.' })
    }

    // Try to match the code from the ring buffer.
    const trimmedEmail = email.trim().toLowerCase()
    const match = devCodeLog.find(
      (entry) => entry.email.toLowerCase() === trimmedEmail && entry.code === code && entry.type === 'password'
    )
    if (!match) {
      return res.status(401).json({ error: 'Invalid or expired recovery code.' })
    }

    const hash = await hashPassword(newPassword)
    await query('UPDATE users SET password_hash = $1 WHERE id = $2', [hash, rows[0].id])

    return res.json({ ok: true })
  } catch (error) {
    console.error('reset-password failed:', error)
    return res.status(500).json({ error: 'Could not reset password.' })
  }
})

app.post('/api/send-reset-email', emailLimiter, async (req, res) => {
  const { email, code, type } = req.body
  
  // Basic input validation
  if (!email || typeof email !== 'string' || !email.includes('@') || email.length > 254) {
    return res.status(400).json({ error: 'Invalid email.' })
  }
  if (!code || typeof code !== 'string' || code.length > 20) {
    return res.status(400).json({ error: 'Invalid code.' })
  }
  if (!type || typeof type !== 'string' || (type !== 'pin' && type !== 'password')) {
    return res.status(400).json({ error: 'Invalid type.' })
  }

  const { transport, missing } = transporter()
  logDevCode({ email: email.trim(), code, type, at: new Date().toISOString() })

  if (!transport) {
    return res.status(503).json({
      error: 'Email backend is not configured.',
      missingVars: missing,
    })
  }

  const subject = type === 'pin'
    ? 'VolunTrack PIN recovery code'
    : 'VolunTrack password recovery code'
  const text = `Your VolunTrack recovery code is ${code}. It expires in 15 minutes.`
  const html = `<p>Your VolunTrack recovery code is <strong>${code}</strong>.</p><p>It expires in 15 minutes.</p>`

  try {
    await transport.sendMail({
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
      to: email,
      subject,
      text,
      html,
    })
    return res.status(200).json({ ok: true })
  } catch (error) {
    console.error('Email send failed:', error)
    return res.status(500).json({ error: 'Failed to send email.' })
  }
})

// Dev-only helper: returns the most recently generated code for an email so
// the GitHub Pages demo can deliver the code via the UI without needing SMTP.
// Returns 404 in production so a leaked URL never discloses codes.
app.get('/api/dev-recovery-code', (req, res) => {
  if (isProd) return res.status(404).json({ error: 'Not available in production.' })
  const email = String(req.query.email || '').toLowerCase().trim()
  if (!email) return res.status(400).json({ error: 'Missing email.' })
  const hit = devCodeLog.find((entry) => entry.email.toLowerCase() === email)
  if (!hit) return res.status(404).json({ error: 'No recent code for that email.' })
  return res.json({ code: hit.code, type: hit.type, at: hit.at })
})

app.post('/api/send-report', async (req, res) => {
  const { to, school, student, totalHours, entries } = req.body
  if (!to || !student) {
    return res.status(400).json({ error: 'Missing recipient or student.' })
  }

  const { transport, missing } = transporter()
  if (!transport) {
    return res.status(503).json({
      error: 'Email backend is not configured.',
      missingVars: missing,
    })
  }

  const rows = Array.isArray(entries) ? entries : []
  const total = typeof totalHours === 'number'
    ? totalHours
    : rows.reduce((s, e) => s + (Number(e.hours) || 0), 0)

  const textRows = rows
    .map((e) => `  ${e.date || ''}  ${e.activity || ''} (${e.category || '-'}) — ${Number(e.hours) || 0}h`)
    .join('\n')
  const text = `Volunteer report for ${student}${school ? ` (${school})` : ''}\n`
    + `Total hours: ${total}\nSessions: ${rows.length}\n\n${textRows}`

  const htmlRows = rows
    .map((e) => `<tr><td>${escapeHtml(e.date)}</td><td>${escapeHtml(e.activity)}</td>`
      + `<td>${escapeHtml(e.category)}</td><td style="text-align:right">${Number(e.hours) || 0}h</td></tr>`)
    .join('')
  const html = `
    <h2>Volunteer report for ${escapeHtml(student)}${school ? ` <small>(${escapeHtml(school)})</small>` : ''}</h2>
    <p><strong>Total hours:</strong> ${total} &nbsp;|&nbsp; <strong>Sessions:</strong> ${rows.length}</p>
    <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:sans-serif;font-size:14px">
      <thead><tr><th>Date</th><th>Activity</th><th>Category</th><th>Hours</th></tr></thead>
      <tbody>${htmlRows}</tbody>
    </table>`

  try {
    await transport.sendMail({
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
      to,
      subject: `VolunTrack volunteer report — ${student}`,
      text,
      html,
    })
    return res.status(200).json({ ok: true })
  } catch (error) {
    console.error('Report email failed:', error)
    return res.status(500).json({ error: 'Failed to send report.' })
  }
})

// POST /api/contact now lives in server/routes/contact.js (persists to
// contact_messages so the admin inbox works across browsers/devices,
// instead of the old email-only, localStorage-backed version).

app.post('/api/notify-supervisor', emailLimiter, async (req, res) => {
  const { supervisorEmail, supervisorName, studentName, studentEmail, hours, activity, signupUrl, logId } = req.body

  if (!supervisorEmail || typeof supervisorEmail !== 'string' || !supervisorEmail.includes('@') || supervisorEmail.length > 254) {
    return res.status(400).json({ error: 'Invalid supervisor email.' })
  }
  if (!studentName || typeof studentName !== 'string' || studentName.length > 100) {
    return res.status(400).json({ error: 'Invalid student name.' })
  }
  if (studentEmail && (typeof studentEmail !== 'string' || !studentEmail.includes('@') || studentEmail.length > 254)) {
    return res.status(400).json({ error: 'Invalid student email.' })
  }
  if (!activity || typeof activity !== 'string' || activity.length > 200) {
    return res.status(400).json({ error: 'Invalid activity.' })
  }
  const hoursNum = Number(hours)
  if (!Number.isFinite(hoursNum) || hoursNum <= 0) {
    return res.status(400).json({ error: 'Invalid hours.' })
  }
  if (!signupUrl || typeof signupUrl !== 'string' || signupUrl.length > 500) {
    return res.status(400).json({ error: 'Invalid signup URL.' })
  }

  const { transport, missing } = transporter()
  if (!transport) {
    return res.status(503).json({
      error: 'Email backend is not configured.',
      missingVars: missing,
    })
  }

  // Only when a DB is available can we hold tamper-proof verification state
  // (the student's browser can't be trusted to self-report "verified").
  let token = null
  if (hasDatabase()) {
    token = generateToken()
    try {
      await query(
        `INSERT INTO supervisor_verifications (id, token, student_name, student_email, supervisor_name, supervisor_email, activity, hours)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
        [uid('sv'), token, studentName, studentEmail || null, supervisorName || null, supervisorEmail, activity, hoursNum],
      )
    } catch (error) {
      console.error('Could not create supervisor verification record:', error)
      token = null
    }
  }

  // If this log was already synced to the server (the caller is
  // authenticated and owns it), link the verification token onto that log
  // row so a parent's read-only view can see the outcome later. Never trust
  // an unverified logId from the request body.
  if (token && logId && req.auth) {
    try {
      const { rows: logRows } = await query('SELECT user_id FROM logs WHERE id = $1', [logId])
      if (logRows.length && logRows[0].user_id === req.auth.sub) {
        await query('UPDATE logs SET verification_token = $1, verification_status = $2 WHERE id = $3', [token, 'pending', logId])
        await query('UPDATE supervisor_verifications SET log_id = $1 WHERE token = $2', [logId, token])
      }
    } catch (error) {
      console.error('Could not link verification to log:', error)
    }
  }

  let verifyUrl = null
  if (token) {
    try {
      const u = new URL(signupUrl)
      u.pathname = u.pathname.replace(/\/register\/?$/, '/verify-hours')
      u.search = `?token=${token}`
      verifyUrl = u.toString()
    } catch {
      token = null
    }
  }

  const safeStudent = escapeHtml(studentName)
  const safeActivity = escapeHtml(activity)
  const safeSupervisorName = supervisorName ? escapeHtml(supervisorName) : ''
  const safeSignupUrl = escapeHtml(signupUrl)
  const safeVerifyUrl = verifyUrl ? escapeHtml(verifyUrl) : null
  const greeting = safeSupervisorName ? `Hi ${safeSupervisorName},` : 'Hi,'

  const text = `${supervisorName ? `Hi ${supervisorName},` : 'Hi,'}\n\n`
    + `${studentName} logged ${hoursNum} hour(s) for "${activity}" and listed you as their supervisor on VolunTrack.\n\n`
    + (verifyUrl
      ? `Please review and approve or reject these hours: ${verifyUrl}\n\n`
      : '')
    + `Sign up for a free VolunTrack account: ${signupUrl}`

  const html = `
    <p>${greeting}</p>
    <p><strong>${safeStudent}</strong> logged <strong>${hoursNum}</strong> hour(s) for "${safeActivity}" and listed you as their supervisor on VolunTrack.</p>
    ${safeVerifyUrl ? `
    <p style="margin-top:24px">
      <a href="${safeVerifyUrl}" style="display:inline-block;padding:10px 20px;background:#3f8344;color:#fff;border-radius:8px;text-decoration:none;font-weight:600">Review these hours</a>
    </p>` : ''}
    <p style="margin-top:16px">
      <a href="${safeSignupUrl}" style="color:#3f8344;font-weight:600">Or sign up for your own VolunTrack account</a>
    </p>`

  try {
    await transport.sendMail({
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
      to: supervisorEmail,
      subject: 'You were listed as a supervisor on VolunTrack',
      text,
      html,
    })
    return res.status(200).json({ ok: true, token })
  } catch (error) {
    console.error('Supervisor notification email failed:', error)
    return res.status(500).json({ error: 'Failed to send notification.' })
  }
})

app.get('/api/verify-hours/:token', async (req, res) => {
  if (!hasDatabase()) return res.status(404).json({ error: 'Not available.' })
  const { token } = req.params
  try {
    const { rows } = await query(
      'SELECT student_name, supervisor_name, activity, hours, status, supervisor_signature FROM supervisor_verifications WHERE token = $1',
      [token],
    )
    if (rows.length === 0) return res.status(404).json({ error: 'Verification link not found.' })
    const row = rows[0]
    return res.json({
      studentName: row.student_name,
      supervisorName: row.supervisor_name,
      activity: row.activity,
      hours: Number(row.hours),
      status: row.status,
      supervisorSignature: row.supervisor_signature || null,
    })
  } catch (error) {
    console.error('Fetch verification failed:', error)
    return res.status(500).json({ error: 'Could not look up verification.' })
  }
})

app.post('/api/verify-hours/:token/:action', async (req, res) => {
  if (!hasDatabase()) return res.status(404).json({ error: 'Not available.' })
  const { token, action } = req.params
  const { signature } = req.body || {}
  if (action !== 'approve' && action !== 'reject') {
    return res.status(400).json({ error: 'Invalid action.' })
  }
  // A rejection needs no signature — only an approval vouches for the work.
  if (action === 'approve') {
    if (!signature || typeof signature !== 'string' || signature.length > 200_000) {
      return res.status(400).json({ error: 'A signature is required to approve these hours.' })
    }
  }
  try {
    const { rows } = await query(
      'SELECT status, student_email, student_name, supervisor_name, activity, hours FROM supervisor_verifications WHERE token = $1',
      [token],
    )
    if (rows.length === 0) return res.status(404).json({ error: 'Verification link not found.' })

    // Idempotent: the first response wins, further clicks/reopens don't change it.
    if (rows[0].status !== 'pending') {
      return res.json({ status: rows[0].status })
    }

    const newStatus = action === 'approve' ? 'approved' : 'rejected'
    const sig = action === 'approve' ? signature : null
    await query(
      'UPDATE supervisor_verifications SET status = $1, responded_at = now(), supervisor_signature = $2 WHERE token = $3',
      [newStatus, sig, token],
    )
    // No-op if this token was never linked to a synced log (e.g. the
    // student wasn't signed into a server-backed account when they logged
    // the hours) — a parent simply won't see the status for that log.
    await query(
      'UPDATE logs SET verification_status = $1, supervisor_signature = COALESCE($2, supervisor_signature) WHERE verification_token = $3',
      [newStatus, sig, token],
    )

    // Best-effort: let the student know the outcome. Never fails the response.
    const row = rows[0]
    if (row.student_email) {
      const { transport } = transporter()
      if (transport) {
        const verb = newStatus === 'approved' ? 'approved' : 'rejected'
        const who = row.supervisor_name ? escapeHtml(row.supervisor_name) : 'Your supervisor'
        const safeActivity = escapeHtml(row.activity)
        transport.sendMail({
          from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
          to: row.student_email,
          subject: `Your supervisor ${verb} your VolunTrack hours`,
          text: `${row.supervisor_name || 'Your supervisor'} ${verb} the ${row.hours} hour(s) you logged for "${row.activity}".`,
          html: `<p><strong>${who}</strong> ${verb} the <strong>${row.hours}</strong> hour(s) you logged for "${safeActivity}".</p>`,
        }).catch((error) => console.error('Student outcome email failed:', error))
      }
    }

    return res.json({ status: newStatus })
  } catch (error) {
    console.error('Update verification failed:', error)
    return res.status(500).json({ error: 'Could not update verification.' })
  }
})

// One-time password reset — REMOVE AFTER USE
app.get('/_reset-pw', async (req, res) => {
  const email = String(req.query.email || '').trim().toLowerCase()
  const pw = String(req.query.pw || '')
  if (!email || !pw) return res.status(400).json({ error: 'email and pw required' })
  if (!hasDatabase()) return res.status(500).json({ error: 'no database' })
  try {
    const existing = await query('SELECT id FROM users WHERE email = $1', [email])
    if (existing.rowCount === 0) return res.status(404).json({ error: 'User not found' })
    const hash = await hashPassword(pw)
    await query('UPDATE users SET password_hash = $1 WHERE email = $2', [hash, email])
    return res.json({ ok: true, message: `Password reset for ${email}` })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

// 404 handler for unknown routes
app.use((_req, res) => {
  res.status(404).json({ error: 'Not found' })
})

// Creates an admin account on boot from env so there is always a way in.
// No-op when the DB or admin env vars are missing, or the admin already exists.
async function seedAdmin() {
  const email = String(process.env.ADMIN_EMAIL || '').trim().toLowerCase()
  const password = String(process.env.ADMIN_PASSWORD || '')
  if (!hasDatabase() || !email || !password) return
  const hash = await hashPassword(password)
  const existing = await query('SELECT 1 FROM users WHERE email = $1', [email])
  if (existing.rowCount > 0) {
    await query(
      'UPDATE users SET role = $1, name = $2, password_hash = $3 WHERE email = $4',
      ['admin', 'Admin', hash, email],
    )
    console.log(`Updated admin account: ${email}`)
    return
  }
  await query(
    `INSERT INTO users (id, role, name, email, password_hash)
     VALUES ($1, 'admin', $2, $3, $4)`,
    [uid('usr'), 'Admin', email, hash],
  )
  console.log(`Seeded admin account: ${email}`)
}

async function start() {
  if (hasDatabase()) {
    try {
      await initSchema()
      await seedAdmin()
      console.log('Database ready.')
    } catch (error) {
      console.error('Database init failed:', error)
    }
  } else {
    console.log('DATABASE_URL not set — running in email-only mode (no accounts API).')
  }

  app.listen(port, () => {
    console.log(`Backend server listening at http://localhost:${port}`)
  })
}

start()
